version: '3.7'
services:
  vehicule-db:
    restart: always
    build: 
      context: .
      target: ms-db
    image: ms-db:v1.0
    container_name: vehicule-db
    env_file:
      - ./.env
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - vehicule-db:/var/lib/postgresql/data
 
volumes:
  vehicule-db:
