version: '3.7'
services:
  atelier-db:
    restart: always
    build: 
      context: .
      target: atelier-db
    image: atelier-db:v1.0
    container_name: atelier-db
    env_file:
      - ./.env
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - atelier-db:/var/lib/postgresql/data
 
volumes:
  atelier-db:
